package soft.idea.hospital.kidny2017.se.models;
// Generated Jan 26, 2017 4:59:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddressDoner generated by hbm2java
 */
@Entity
@Table(name="address_doner"
    ,catalog="safenets_host_se"
)
public class AddressDoner  implements java.io.Serializable {


     private Integer idaddressDoner;
     private Doner doner;
     private String addressDonerNo;
     private String addressDonerStreet;
     private String addressDonerTown;

    public AddressDoner() {
    }

	
    public AddressDoner(Doner doner) {
        this.doner = doner;
    }
    public AddressDoner(Doner doner, String addressDonerNo, String addressDonerStreet, String addressDonerTown) {
       this.doner = doner;
       this.addressDonerNo = addressDonerNo;
       this.addressDonerStreet = addressDonerStreet;
       this.addressDonerTown = addressDonerTown;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idaddress_doner", unique=true, nullable=false)
    public Integer getIdaddressDoner() {
        return this.idaddressDoner;
    }
    
    public void setIdaddressDoner(Integer idaddressDoner) {
        this.idaddressDoner = idaddressDoner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doner_iddoner", nullable=false)
    public Doner getDoner() {
        return this.doner;
    }
    
    public void setDoner(Doner doner) {
        this.doner = doner;
    }

    
    @Column(name="address_doner_no", length=45)
    public String getAddressDonerNo() {
        return this.addressDonerNo;
    }
    
    public void setAddressDonerNo(String addressDonerNo) {
        this.addressDonerNo = addressDonerNo;
    }

    
    @Column(name="address_doner_street", length=45)
    public String getAddressDonerStreet() {
        return this.addressDonerStreet;
    }
    
    public void setAddressDonerStreet(String addressDonerStreet) {
        this.addressDonerStreet = addressDonerStreet;
    }

    
    @Column(name="address_doner_town", length=45)
    public String getAddressDonerTown() {
        return this.addressDonerTown;
    }
    
    public void setAddressDonerTown(String addressDonerTown) {
        this.addressDonerTown = addressDonerTown;
    }




}


