package soft.idea.hospital.kidny2017.se.models;
// Generated Feb 21, 2017 7:13:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CadaverType generated by hbm2java
 */
@Entity
@Table(name="cadaver_type"
    ,catalog="safenets_host_se"
)
public class CadaverType  implements java.io.Serializable {


     private Integer idcadaverType;
     private String cadaverTypeName;
     private String cadaverTypeStatus;
     private Set<Doner> doners = new HashSet<Doner>(0);

    public CadaverType() {
    }

    public CadaverType(String cadaverTypeName, String cadaverTypeStatus, Set<Doner> doners) {
       this.cadaverTypeName = cadaverTypeName;
       this.cadaverTypeStatus = cadaverTypeStatus;
       this.doners = doners;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcadaver_type", unique=true, nullable=false)
    public Integer getIdcadaverType() {
        return this.idcadaverType;
    }
    
    public void setIdcadaverType(Integer idcadaverType) {
        this.idcadaverType = idcadaverType;
    }

    
    @Column(name="cadaver_type_name", length=45)
    public String getCadaverTypeName() {
        return this.cadaverTypeName;
    }
    
    public void setCadaverTypeName(String cadaverTypeName) {
        this.cadaverTypeName = cadaverTypeName;
    }

    
    @Column(name="cadaver_type_status", length=45)
    public String getCadaverTypeStatus() {
        return this.cadaverTypeStatus;
    }
    
    public void setCadaverTypeStatus(String cadaverTypeStatus) {
        this.cadaverTypeStatus = cadaverTypeStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadaverType")
    public Set<Doner> getDoners() {
        return this.doners;
    }
    
    public void setDoners(Set<Doner> doners) {
        this.doners = doners;
    }




}


