package soft.idea.hospital.kidny2017.se.models;
// Generated Mar 4, 2017 7:52:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DonerHostpital generated by hbm2java
 */
@Entity
@Table(name="doner_hostpital"
    ,catalog="safenets_host_se"
)
public class DonerHostpital  implements java.io.Serializable {


     private Integer iddonerHostpital;
     private String donerHostpitalName;
     private String donerHostpitalProvince;
     private String donerHostpitalDistric;
     private String donerHostpitalStatus;
     private Set<Doner> doners = new HashSet<Doner>(0);

    public DonerHostpital() {
    }

    public DonerHostpital(String donerHostpitalName, String donerHostpitalProvince, String donerHostpitalDistric, String donerHostpitalStatus, Set<Doner> doners) {
       this.donerHostpitalName = donerHostpitalName;
       this.donerHostpitalProvince = donerHostpitalProvince;
       this.donerHostpitalDistric = donerHostpitalDistric;
       this.donerHostpitalStatus = donerHostpitalStatus;
       this.doners = doners;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddoner_hostpital", unique=true, nullable=false)
    public Integer getIddonerHostpital() {
        return this.iddonerHostpital;
    }
    
    public void setIddonerHostpital(Integer iddonerHostpital) {
        this.iddonerHostpital = iddonerHostpital;
    }

    
    @Column(name="doner_hostpital_name", length=45)
    public String getDonerHostpitalName() {
        return this.donerHostpitalName;
    }
    
    public void setDonerHostpitalName(String donerHostpitalName) {
        this.donerHostpitalName = donerHostpitalName;
    }

    
    @Column(name="doner_hostpital_province", length=45)
    public String getDonerHostpitalProvince() {
        return this.donerHostpitalProvince;
    }
    
    public void setDonerHostpitalProvince(String donerHostpitalProvince) {
        this.donerHostpitalProvince = donerHostpitalProvince;
    }

    
    @Column(name="doner_hostpital_distric", length=45)
    public String getDonerHostpitalDistric() {
        return this.donerHostpitalDistric;
    }
    
    public void setDonerHostpitalDistric(String donerHostpitalDistric) {
        this.donerHostpitalDistric = donerHostpitalDistric;
    }

    
    @Column(name="doner_hostpital_status", length=45)
    public String getDonerHostpitalStatus() {
        return this.donerHostpitalStatus;
    }
    
    public void setDonerHostpitalStatus(String donerHostpitalStatus) {
        this.donerHostpitalStatus = donerHostpitalStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="donerHostpital")
    public Set<Doner> getDoners() {
        return this.doners;
    }
    
    public void setDoners(Set<Doner> doners) {
        this.doners = doners;
    }




}


