package soft.idea.hospital.kidny2017.se.models;
// Generated Jan 26, 2017 4:59:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doner generated by hbm2java
 */
@Entity
@Table(name="doner"
    ,catalog="safenets_host_se"
)
public class Doner  implements java.io.Serializable {


     private Integer iddoner;
     private BlodGroup blodGroup;
     private CadaverType cadaverType;
     private Institution institution;
     private SubWhiteBloadPlates subWhiteBloadPlates;
     private Virology virology;
     private String donerFname;
     private String donerMname;
     private String donerLname;
     private String donerGen;
     private String donerNic;
     private String donerDob;
     private String donerRegdate;
     private String donerRhesusFactor;
     private String donerWeight;
     private String donerHeight;
     private String donerIdentity;
     private String donerPhone;
     private String donerCauseOfDeath;
     private String donerBrainDeathDate;
     private String donerCuntry;
     private String donerPastHistory;
     private String donerPresenceOfSepsis;
     private Integer donerAge;
     private String donerIcuDays;
     private Integer donerBmi;
     private Integer donerSteatoticLiver;
     private Integer donerSodiam;
     private Integer donerSgpt;
     private Integer donerSgot;
     private Integer donerBilirubin;
     private String donerStatus;
     private Set<AddressDoner> addressDoners = new HashSet<AddressDoner>(0);
     private Set<DonerHostpital> donerHostpitals = new HashSet<DonerHostpital>(0);

    public Doner() {
    }

	
    public Doner(BlodGroup blodGroup, CadaverType cadaverType, Institution institution, SubWhiteBloadPlates subWhiteBloadPlates, Virology virology) {
        this.blodGroup = blodGroup;
        this.cadaverType = cadaverType;
        this.institution = institution;
        this.subWhiteBloadPlates = subWhiteBloadPlates;
        this.virology = virology;
    }
    public Doner(BlodGroup blodGroup, CadaverType cadaverType, Institution institution, SubWhiteBloadPlates subWhiteBloadPlates, Virology virology, String donerFname, String donerMname, String donerLname, String donerGen, String donerNic, String donerDob, String donerRegdate, String donerRhesusFactor, String donerWeight, String donerHeight, String donerIdentity, String donerPhone, String donerCauseOfDeath, String donerBrainDeathDate, String donerCuntry, String donerPastHistory, String donerPresenceOfSepsis, Integer donerAge, String donerIcuDays, Integer donerBmi, Integer donerSteatoticLiver, Integer donerSodiam, Integer donerSgpt, Integer donerSgot, Integer donerBilirubin, String donerStatus, Set<AddressDoner> addressDoners, Set<DonerHostpital> donerHostpitals) {
       this.blodGroup = blodGroup;
       this.cadaverType = cadaverType;
       this.institution = institution;
       this.subWhiteBloadPlates = subWhiteBloadPlates;
       this.virology = virology;
       this.donerFname = donerFname;
       this.donerMname = donerMname;
       this.donerLname = donerLname;
       this.donerGen = donerGen;
       this.donerNic = donerNic;
       this.donerDob = donerDob;
       this.donerRegdate = donerRegdate;
       this.donerRhesusFactor = donerRhesusFactor;
       this.donerWeight = donerWeight;
       this.donerHeight = donerHeight;
       this.donerIdentity = donerIdentity;
       this.donerPhone = donerPhone;
       this.donerCauseOfDeath = donerCauseOfDeath;
       this.donerBrainDeathDate = donerBrainDeathDate;
       this.donerCuntry = donerCuntry;
       this.donerPastHistory = donerPastHistory;
       this.donerPresenceOfSepsis = donerPresenceOfSepsis;
       this.donerAge = donerAge;
       this.donerIcuDays = donerIcuDays;
       this.donerBmi = donerBmi;
       this.donerSteatoticLiver = donerSteatoticLiver;
       this.donerSodiam = donerSodiam;
       this.donerSgpt = donerSgpt;
       this.donerSgot = donerSgot;
       this.donerBilirubin = donerBilirubin;
       this.donerStatus = donerStatus;
       this.addressDoners = addressDoners;
       this.donerHostpitals = donerHostpitals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddoner", unique=true, nullable=false)
    public Integer getIddoner() {
        return this.iddoner;
    }
    
    public void setIddoner(Integer iddoner) {
        this.iddoner = iddoner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="blod_group_idblod_group", nullable=false)
    public BlodGroup getBlodGroup() {
        return this.blodGroup;
    }
    
    public void setBlodGroup(BlodGroup blodGroup) {
        this.blodGroup = blodGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cadaver_type_idcadaver_type", nullable=false)
    public CadaverType getCadaverType() {
        return this.cadaverType;
    }
    
    public void setCadaverType(CadaverType cadaverType) {
        this.cadaverType = cadaverType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="institution_idinstitution", nullable=false)
    public Institution getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(Institution institution) {
        this.institution = institution;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub_white_bload_plates_idsub_white_bload_plates", nullable=false)
    public SubWhiteBloadPlates getSubWhiteBloadPlates() {
        return this.subWhiteBloadPlates;
    }
    
    public void setSubWhiteBloadPlates(SubWhiteBloadPlates subWhiteBloadPlates) {
        this.subWhiteBloadPlates = subWhiteBloadPlates;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="virology_idvirology", nullable=false)
    public Virology getVirology() {
        return this.virology;
    }
    
    public void setVirology(Virology virology) {
        this.virology = virology;
    }

    
    @Column(name="doner_fname", length=45)
    public String getDonerFname() {
        return this.donerFname;
    }
    
    public void setDonerFname(String donerFname) {
        this.donerFname = donerFname;
    }

    
    @Column(name="doner_mname", length=45)
    public String getDonerMname() {
        return this.donerMname;
    }
    
    public void setDonerMname(String donerMname) {
        this.donerMname = donerMname;
    }

    
    @Column(name="doner_lname", length=45)
    public String getDonerLname() {
        return this.donerLname;
    }
    
    public void setDonerLname(String donerLname) {
        this.donerLname = donerLname;
    }

    
    @Column(name="doner_gen", length=45)
    public String getDonerGen() {
        return this.donerGen;
    }
    
    public void setDonerGen(String donerGen) {
        this.donerGen = donerGen;
    }

    
    @Column(name="doner_nic", length=45)
    public String getDonerNic() {
        return this.donerNic;
    }
    
    public void setDonerNic(String donerNic) {
        this.donerNic = donerNic;
    }

    
    @Column(name="doner_dob", length=45)
    public String getDonerDob() {
        return this.donerDob;
    }
    
    public void setDonerDob(String donerDob) {
        this.donerDob = donerDob;
    }

    
    @Column(name="doner_regdate", length=45)
    public String getDonerRegdate() {
        return this.donerRegdate;
    }
    
    public void setDonerRegdate(String donerRegdate) {
        this.donerRegdate = donerRegdate;
    }

    
    @Column(name="doner_rhesus_factor", length=45)
    public String getDonerRhesusFactor() {
        return this.donerRhesusFactor;
    }
    
    public void setDonerRhesusFactor(String donerRhesusFactor) {
        this.donerRhesusFactor = donerRhesusFactor;
    }

    
    @Column(name="doner_weight", length=45)
    public String getDonerWeight() {
        return this.donerWeight;
    }
    
    public void setDonerWeight(String donerWeight) {
        this.donerWeight = donerWeight;
    }

    
    @Column(name="doner_height", length=45)
    public String getDonerHeight() {
        return this.donerHeight;
    }
    
    public void setDonerHeight(String donerHeight) {
        this.donerHeight = donerHeight;
    }

    
    @Column(name="doner_identity", length=45)
    public String getDonerIdentity() {
        return this.donerIdentity;
    }
    
    public void setDonerIdentity(String donerIdentity) {
        this.donerIdentity = donerIdentity;
    }

    
    @Column(name="doner_phone", length=45)
    public String getDonerPhone() {
        return this.donerPhone;
    }
    
    public void setDonerPhone(String donerPhone) {
        this.donerPhone = donerPhone;
    }

    
    @Column(name="doner_cause_of_death", length=45)
    public String getDonerCauseOfDeath() {
        return this.donerCauseOfDeath;
    }
    
    public void setDonerCauseOfDeath(String donerCauseOfDeath) {
        this.donerCauseOfDeath = donerCauseOfDeath;
    }

    
    @Column(name="doner_brain_death_date", length=45)
    public String getDonerBrainDeathDate() {
        return this.donerBrainDeathDate;
    }
    
    public void setDonerBrainDeathDate(String donerBrainDeathDate) {
        this.donerBrainDeathDate = donerBrainDeathDate;
    }

    
    @Column(name="doner_cuntry", length=45)
    public String getDonerCuntry() {
        return this.donerCuntry;
    }
    
    public void setDonerCuntry(String donerCuntry) {
        this.donerCuntry = donerCuntry;
    }

    
    @Column(name="doner_past_history")
    public String getDonerPastHistory() {
        return this.donerPastHistory;
    }
    
    public void setDonerPastHistory(String donerPastHistory) {
        this.donerPastHistory = donerPastHistory;
    }

    
    @Column(name="doner_presence_of_sepsis")
    public String getDonerPresenceOfSepsis() {
        return this.donerPresenceOfSepsis;
    }
    
    public void setDonerPresenceOfSepsis(String donerPresenceOfSepsis) {
        this.donerPresenceOfSepsis = donerPresenceOfSepsis;
    }

    
    @Column(name="doner_age")
    public Integer getDonerAge() {
        return this.donerAge;
    }
    
    public void setDonerAge(Integer donerAge) {
        this.donerAge = donerAge;
    }

    
    @Column(name="doner_icu_days", length=45)
    public String getDonerIcuDays() {
        return this.donerIcuDays;
    }
    
    public void setDonerIcuDays(String donerIcuDays) {
        this.donerIcuDays = donerIcuDays;
    }

    
    @Column(name="doner_bmi")
    public Integer getDonerBmi() {
        return this.donerBmi;
    }
    
    public void setDonerBmi(Integer donerBmi) {
        this.donerBmi = donerBmi;
    }

    
    @Column(name="doner_steatotic_liver")
    public Integer getDonerSteatoticLiver() {
        return this.donerSteatoticLiver;
    }
    
    public void setDonerSteatoticLiver(Integer donerSteatoticLiver) {
        this.donerSteatoticLiver = donerSteatoticLiver;
    }

    
    @Column(name="doner_sodiam")
    public Integer getDonerSodiam() {
        return this.donerSodiam;
    }
    
    public void setDonerSodiam(Integer donerSodiam) {
        this.donerSodiam = donerSodiam;
    }

    
    @Column(name="doner_sgpt")
    public Integer getDonerSgpt() {
        return this.donerSgpt;
    }
    
    public void setDonerSgpt(Integer donerSgpt) {
        this.donerSgpt = donerSgpt;
    }

    
    @Column(name="doner_sgot")
    public Integer getDonerSgot() {
        return this.donerSgot;
    }
    
    public void setDonerSgot(Integer donerSgot) {
        this.donerSgot = donerSgot;
    }

    
    @Column(name="doner_bilirubin")
    public Integer getDonerBilirubin() {
        return this.donerBilirubin;
    }
    
    public void setDonerBilirubin(Integer donerBilirubin) {
        this.donerBilirubin = donerBilirubin;
    }

    
    @Column(name="doner_status", length=45)
    public String getDonerStatus() {
        return this.donerStatus;
    }
    
    public void setDonerStatus(String donerStatus) {
        this.donerStatus = donerStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doner")
    public Set<AddressDoner> getAddressDoners() {
        return this.addressDoners;
    }
    
    public void setAddressDoners(Set<AddressDoner> addressDoners) {
        this.addressDoners = addressDoners;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doner")
    public Set<DonerHostpital> getDonerHostpitals() {
        return this.donerHostpitals;
    }
    
    public void setDonerHostpitals(Set<DonerHostpital> donerHostpitals) {
        this.donerHostpitals = donerHostpitals;
    }




}


