package soft.idea.hospital.kidny2017.se.models;
// Generated Jan 26, 2017 4:59:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Institution generated by hbm2java
 */
@Entity
@Table(name="institution"
    ,catalog="safenets_host_se"
)
public class Institution  implements java.io.Serializable {


     private Integer idinstitution;
     private String institutionName;
     private String institutionStatus;
     private Set<Doner> doners = new HashSet<Doner>(0);
     private Set<Pation> pations = new HashSet<Pation>(0);

    public Institution() {
    }

    public Institution(String institutionName, String institutionStatus, Set<Doner> doners, Set<Pation> pations) {
       this.institutionName = institutionName;
       this.institutionStatus = institutionStatus;
       this.doners = doners;
       this.pations = pations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idinstitution", unique=true, nullable=false)
    public Integer getIdinstitution() {
        return this.idinstitution;
    }
    
    public void setIdinstitution(Integer idinstitution) {
        this.idinstitution = idinstitution;
    }

    
    @Column(name="institution_name", length=45)
    public String getInstitutionName() {
        return this.institutionName;
    }
    
    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    
    @Column(name="institution_status", length=45)
    public String getInstitutionStatus() {
        return this.institutionStatus;
    }
    
    public void setInstitutionStatus(String institutionStatus) {
        this.institutionStatus = institutionStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="institution")
    public Set<Doner> getDoners() {
        return this.doners;
    }
    
    public void setDoners(Set<Doner> doners) {
        this.doners = doners;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="institution")
    public Set<Pation> getPations() {
        return this.pations;
    }
    
    public void setPations(Set<Pation> pations) {
        this.pations = pations;
    }




}


