package soft.idea.hospital.kidny2017.se.models;
// Generated Feb 21, 2017 8:45:30 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PationHasDoner generated by hbm2java
 */
@Entity
@Table(name="pation_has_doner"
    ,catalog="safenets_host_se"
)
public class PationHasDoner  implements java.io.Serializable {


     private int pationHasDonerId;
     private Doner doner;
     private Pation pation;

    public PationHasDoner() {
    }

    public PationHasDoner(int pationHasDonerId, Doner doner, Pation pation) {
       this.pationHasDonerId = pationHasDonerId;
       this.doner = doner;
       this.pation = pation;
    }
   
     @Id 

    
    @Column(name="pation_has_doner_id", unique=true, nullable=false)
    public int getPationHasDonerId() {
        return this.pationHasDonerId;
    }
    
    public void setPationHasDonerId(int pationHasDonerId) {
        this.pationHasDonerId = pationHasDonerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doner_iddoner", nullable=false)
    public Doner getDoner() {
        return this.doner;
    }
    
    public void setDoner(Doner doner) {
        this.doner = doner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pation_idpation", nullable=false)
    public Pation getPation() {
        return this.pation;
    }
    
    public void setPation(Pation pation) {
        this.pation = pation;
    }




}


