package soft.idea.hospital.kidny2017.se.models;
// Generated Mar 4, 2017 7:52:38 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PationHasDoner generated by hbm2java
 */
@Entity
@Table(name="pation_has_doner"
    ,catalog="safenets_host_se"
)
public class PationHasDoner  implements java.io.Serializable {


     private int pationHasDonerId;
     private Doner doner;
     private Pation pation;
     private String pationHasDonerStatus;
     private String pationHasDonerCompleteStatus;

    public PationHasDoner() {
    }

	
    public PationHasDoner(int pationHasDonerId, Doner doner, Pation pation) {
        this.pationHasDonerId = pationHasDonerId;
        this.doner = doner;
        this.pation = pation;
    }
    public PationHasDoner(int pationHasDonerId, Doner doner, Pation pation, String pationHasDonerStatus, String pationHasDonerCompleteStatus) {
       this.pationHasDonerId = pationHasDonerId;
       this.doner = doner;
       this.pation = pation;
       this.pationHasDonerStatus = pationHasDonerStatus;
       this.pationHasDonerCompleteStatus = pationHasDonerCompleteStatus;
    }
   
     @Id 

    
    @Column(name="pation_has_doner_id", unique=true, nullable=false)
    public int getPationHasDonerId() {
        return this.pationHasDonerId;
    }
    
    public void setPationHasDonerId(int pationHasDonerId) {
        this.pationHasDonerId = pationHasDonerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doner_iddoner", nullable=false)
    public Doner getDoner() {
        return this.doner;
    }
    
    public void setDoner(Doner doner) {
        this.doner = doner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pation_idpation", nullable=false)
    public Pation getPation() {
        return this.pation;
    }
    
    public void setPation(Pation pation) {
        this.pation = pation;
    }

    
    @Column(name="pation_has_doner_status", length=45)
    public String getPationHasDonerStatus() {
        return this.pationHasDonerStatus;
    }
    
    public void setPationHasDonerStatus(String pationHasDonerStatus) {
        this.pationHasDonerStatus = pationHasDonerStatus;
    }

    
    @Column(name="pation_has_doner_complete_status", length=45)
    public String getPationHasDonerCompleteStatus() {
        return this.pationHasDonerCompleteStatus;
    }
    
    public void setPationHasDonerCompleteStatus(String pationHasDonerCompleteStatus) {
        this.pationHasDonerCompleteStatus = pationHasDonerCompleteStatus;
    }




}


