package soft.idea.hospital.kidny2017.se.models;
// Generated Feb 21, 2017 7:13:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pation generated by hbm2java
 */
@Entity
@Table(name="pation"
    ,catalog="safenets_host_se"
)
public class Pation  implements java.io.Serializable {


     private Integer idpation;
     private BlodGroup blodGroup;
     private Institution institution;
     private RhesusFactor rhesusFactor;
     private String pationFname;
     private String pationMname;
     private String pationLname;
     private String pationGen;
     private String pationNic;
     private String pationDob;
     private String pationRegdate;
     private String pationWeight;
     private String pationHeight;
     private String pationIdentity;
     private String pationPhone;
     private String pationStatus;
     private Set<AddressPation> addressPations = new HashSet<AddressPation>(0);

    public Pation() {
    }

	
    public Pation(BlodGroup blodGroup, Institution institution, RhesusFactor rhesusFactor) {
        this.blodGroup = blodGroup;
        this.institution = institution;
        this.rhesusFactor = rhesusFactor;
    }
    public Pation(BlodGroup blodGroup, Institution institution, RhesusFactor rhesusFactor, String pationFname, String pationMname, String pationLname, String pationGen, String pationNic, String pationDob, String pationRegdate, String pationWeight, String pationHeight, String pationIdentity, String pationPhone, String pationStatus, Set<AddressPation> addressPations) {
       this.blodGroup = blodGroup;
       this.institution = institution;
       this.rhesusFactor = rhesusFactor;
       this.pationFname = pationFname;
       this.pationMname = pationMname;
       this.pationLname = pationLname;
       this.pationGen = pationGen;
       this.pationNic = pationNic;
       this.pationDob = pationDob;
       this.pationRegdate = pationRegdate;
       this.pationWeight = pationWeight;
       this.pationHeight = pationHeight;
       this.pationIdentity = pationIdentity;
       this.pationPhone = pationPhone;
       this.pationStatus = pationStatus;
       this.addressPations = addressPations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpation", unique=true, nullable=false)
    public Integer getIdpation() {
        return this.idpation;
    }
    
    public void setIdpation(Integer idpation) {
        this.idpation = idpation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="blod_group_idblod_group", nullable=false)
    public BlodGroup getBlodGroup() {
        return this.blodGroup;
    }
    
    public void setBlodGroup(BlodGroup blodGroup) {
        this.blodGroup = blodGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="institution_idinstitution", nullable=false)
    public Institution getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(Institution institution) {
        this.institution = institution;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rhesus_factor_idrhesus_factor", nullable=false)
    public RhesusFactor getRhesusFactor() {
        return this.rhesusFactor;
    }
    
    public void setRhesusFactor(RhesusFactor rhesusFactor) {
        this.rhesusFactor = rhesusFactor;
    }

    
    @Column(name="pation_fname", length=45)
    public String getPationFname() {
        return this.pationFname;
    }
    
    public void setPationFname(String pationFname) {
        this.pationFname = pationFname;
    }

    
    @Column(name="pation_mname", length=45)
    public String getPationMname() {
        return this.pationMname;
    }
    
    public void setPationMname(String pationMname) {
        this.pationMname = pationMname;
    }

    
    @Column(name="pation_lname", length=45)
    public String getPationLname() {
        return this.pationLname;
    }
    
    public void setPationLname(String pationLname) {
        this.pationLname = pationLname;
    }

    
    @Column(name="pation_gen", length=45)
    public String getPationGen() {
        return this.pationGen;
    }
    
    public void setPationGen(String pationGen) {
        this.pationGen = pationGen;
    }

    
    @Column(name="pation_nic", length=45)
    public String getPationNic() {
        return this.pationNic;
    }
    
    public void setPationNic(String pationNic) {
        this.pationNic = pationNic;
    }

    
    @Column(name="pation_dob", length=45)
    public String getPationDob() {
        return this.pationDob;
    }
    
    public void setPationDob(String pationDob) {
        this.pationDob = pationDob;
    }

    
    @Column(name="pation_regdate", length=45)
    public String getPationRegdate() {
        return this.pationRegdate;
    }
    
    public void setPationRegdate(String pationRegdate) {
        this.pationRegdate = pationRegdate;
    }

    
    @Column(name="pation_weight", length=45)
    public String getPationWeight() {
        return this.pationWeight;
    }
    
    public void setPationWeight(String pationWeight) {
        this.pationWeight = pationWeight;
    }

    
    @Column(name="pation_height", length=45)
    public String getPationHeight() {
        return this.pationHeight;
    }
    
    public void setPationHeight(String pationHeight) {
        this.pationHeight = pationHeight;
    }

    
    @Column(name="pation_identity", length=45)
    public String getPationIdentity() {
        return this.pationIdentity;
    }
    
    public void setPationIdentity(String pationIdentity) {
        this.pationIdentity = pationIdentity;
    }

    
    @Column(name="pation_phone", length=45)
    public String getPationPhone() {
        return this.pationPhone;
    }
    
    public void setPationPhone(String pationPhone) {
        this.pationPhone = pationPhone;
    }

    
    @Column(name="pation_status", length=45)
    public String getPationStatus() {
        return this.pationStatus;
    }
    
    public void setPationStatus(String pationStatus) {
        this.pationStatus = pationStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pation")
    public Set<AddressPation> getAddressPations() {
        return this.addressPations;
    }
    
    public void setAddressPations(Set<AddressPation> addressPations) {
        this.addressPations = addressPations;
    }




}


