package soft.idea.hospital.kidny2017.se.models;
// Generated Feb 21, 2017 7:13:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RhesusFactor generated by hbm2java
 */
@Entity
@Table(name="rhesus_factor"
    ,catalog="safenets_host_se"
)
public class RhesusFactor  implements java.io.Serializable {


     private Integer idrhesusFactor;
     private String rhesusFactorName;
     private String rhesusFactorStatus;
     private Set<Pation> pations = new HashSet<Pation>(0);

    public RhesusFactor() {
    }

    public RhesusFactor(String rhesusFactorName, String rhesusFactorStatus, Set<Pation> pations) {
       this.rhesusFactorName = rhesusFactorName;
       this.rhesusFactorStatus = rhesusFactorStatus;
       this.pations = pations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idrhesus_factor", unique=true, nullable=false)
    public Integer getIdrhesusFactor() {
        return this.idrhesusFactor;
    }
    
    public void setIdrhesusFactor(Integer idrhesusFactor) {
        this.idrhesusFactor = idrhesusFactor;
    }

    
    @Column(name="rhesus_factor_name", length=45)
    public String getRhesusFactorName() {
        return this.rhesusFactorName;
    }
    
    public void setRhesusFactorName(String rhesusFactorName) {
        this.rhesusFactorName = rhesusFactorName;
    }

    
    @Column(name="rhesus_factor_status", length=45)
    public String getRhesusFactorStatus() {
        return this.rhesusFactorStatus;
    }
    
    public void setRhesusFactorStatus(String rhesusFactorStatus) {
        this.rhesusFactorStatus = rhesusFactorStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rhesusFactor")
    public Set<Pation> getPations() {
        return this.pations;
    }
    
    public void setPations(Set<Pation> pations) {
        this.pations = pations;
    }




}


