package soft.idea.hospital.kidny2017.se.models;
// Generated Feb 21, 2017 8:45:30 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="safenets_host_se"
)
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String userName;
     private String userEmail;
     private String userPw;
     private Integer userPhone;
     private String userStatus;

    public User() {
    }

    public User(String userName, String userEmail, String userPw, Integer userPhone, String userStatus) {
       this.userName = userName;
       this.userEmail = userEmail;
       this.userPw = userPw;
       this.userPhone = userPhone;
       this.userStatus = userStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iduser", unique=true, nullable=false)
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="user_name", length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_email", length=45)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="user_pw", length=45)
    public String getUserPw() {
        return this.userPw;
    }
    
    public void setUserPw(String userPw) {
        this.userPw = userPw;
    }

    
    @Column(name="user_phone")
    public Integer getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(Integer userPhone) {
        this.userPhone = userPhone;
    }

    
    @Column(name="user_status", length=45)
    public String getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }




}


