package soft.idea.hospital.kidny2017.se.models;
// Generated Jan 26, 2017 4:59:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Virology generated by hbm2java
 */
@Entity
@Table(name="virology"
    ,catalog="safenets_host_se"
)
public class Virology  implements java.io.Serializable {


     private Integer idvirology;
     private String virologyName;
     private String virologyStatus;
     private Set<Doner> doners = new HashSet<Doner>(0);

    public Virology() {
    }

    public Virology(String virologyName, String virologyStatus, Set<Doner> doners) {
       this.virologyName = virologyName;
       this.virologyStatus = virologyStatus;
       this.doners = doners;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvirology", unique=true, nullable=false)
    public Integer getIdvirology() {
        return this.idvirology;
    }
    
    public void setIdvirology(Integer idvirology) {
        this.idvirology = idvirology;
    }

    
    @Column(name="virology_name", length=45)
    public String getVirologyName() {
        return this.virologyName;
    }
    
    public void setVirologyName(String virologyName) {
        this.virologyName = virologyName;
    }

    
    @Column(name="virology_status", length=45)
    public String getVirologyStatus() {
        return this.virologyStatus;
    }
    
    public void setVirologyStatus(String virologyStatus) {
        this.virologyStatus = virologyStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="virology")
    public Set<Doner> getDoners() {
        return this.doners;
    }
    
    public void setDoners(Set<Doner> doners) {
        this.doners = doners;
    }




}


