/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soft.idea.hospital.kidny2017.se.donner;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import soft.idea.hospital.kidny2017.se.patient.*;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import org.hibernate.Criteria;
import org.hibernate.Hibernate;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;
import sft.idea.hospital.kidny2017.se.supportive_sources.data;
import soft.idea.hospital.kidny2017.se.controler.HibernateUtil;
import soft.idea.hospital.kidny2017.se.models.AddressDoner;
import soft.idea.hospital.kidny2017.se.models.Doner;
import soft.idea.hospital.kidny2017.se.models.DonerHostpital;

/**
 *
 * @author deepalsuranga
 */
public class index extends javax.swing.JPanel {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        loadCuntrys();
        loadHospitals("WP");
        loadHLA("Class 1");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg_hiv = new javax.swing.ButtonGroup();
        bg_hbv = new javax.swing.ButtonGroup();
        bg_hcv = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_mname = new javax.swing.JTextField();
        tf_fname = new javax.swing.JTextField();
        tf_lname = new javax.swing.JTextField();
        tf_nic = new javax.swing.JTextField();
        tf_weight = new javax.swing.JTextField();
        tf_height = new javax.swing.JTextField();
        tf_pno = new javax.swing.JTextField();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        cb_citizenship = new javax.swing.JComboBox<>();
        cb_donnerHospital = new javax.swing.JComboBox<>();
        cb_bloadgroup = new javax.swing.JComboBox<>();
        bt_save = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf_addressNo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_addressStreet = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_addressTown = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_causeOfDeth = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_brain_deth_date = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_icu = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_bmi = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_sgot = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf_sgpt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_liver = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_sodiam = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_bilirubin = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_cadaverType = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        tf_whiteBlodPlates = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_historyOfDrug = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_historyOfMalignancies = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        rb_hiv_yes = new javax.swing.JRadioButton();
        rb_hiv_no = new javax.swing.JRadioButton();
        rb_hbv_yes = new javax.swing.JRadioButton();
        rb_hbv_no = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        rb_hcv_yes = new javax.swing.JRadioButton();
        rb_hcv_no = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        cb_hla_class_type = new javax.swing.JComboBox<>();
        cb_hla_class = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        cb_dsa_class = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        tf_pra = new javax.swing.JTextField();
        cb_donnerHospita_province = new javax.swing.JComboBox<>();
        dc_dob = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(250, 250, 250));
        setMaximumSize(new java.awt.Dimension(1366, 663));
        setMinimumSize(new java.awt.Dimension(1366, 663));

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel1.setText("First Name");

        jLabel2.setBackground(new java.awt.Color(250, 250, 250));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel2.setText("Middle Name");

        jLabel3.setBackground(new java.awt.Color(250, 250, 250));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setBackground(new java.awt.Color(250, 250, 250));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel4.setText("NIC");

        jLabel5.setBackground(new java.awt.Color(250, 250, 250));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel5.setText("Date Of Birth");

        jLabel6.setBackground(new java.awt.Color(250, 250, 250));
        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel6.setText("Gender");

        jLabel7.setBackground(new java.awt.Color(250, 250, 250));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel7.setText("Weight");

        jLabel8.setBackground(new java.awt.Color(250, 250, 250));
        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel8.setText("Height");

        jLabel9.setBackground(new java.awt.Color(250, 250, 250));
        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel9.setText("Citizenship");

        jLabel10.setBackground(new java.awt.Color(250, 250, 250));
        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel10.setText("Phone Number");

        jLabel11.setBackground(new java.awt.Color(250, 250, 250));
        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel11.setText("Donor Hospital");

        jLabel12.setBackground(new java.awt.Color(250, 250, 250));
        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel12.setText("Blod Group");

        tf_mname.setBackground(new java.awt.Color(250, 250, 250));
        tf_mname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_mname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_mname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_fname.setBackground(new java.awt.Color(250, 250, 250));
        tf_fname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_fname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_lname.setBackground(new java.awt.Color(250, 250, 250));
        tf_lname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_lname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_nic.setBackground(new java.awt.Color(250, 250, 250));
        tf_nic.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_nic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_nic.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_weight.setBackground(new java.awt.Color(250, 250, 250));
        tf_weight.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_weight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_weight.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_height.setBackground(new java.awt.Color(250, 250, 250));
        tf_height.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_height.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_height.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_pno.setBackground(new java.awt.Color(250, 250, 250));
        tf_pno.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_pno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_pno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        rb_male.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(rb_male);
        rb_male.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        rb_male.setSelected(true);
        rb_male.setText("Male");
        rb_male.setFocusable(false);

        rb_female.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(rb_female);
        rb_female.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        rb_female.setText("Female");
        rb_female.setFocusable(false);

        cb_citizenship.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cb_citizenship.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_citizenship.setRequestFocusEnabled(false);

        cb_donnerHospital.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cb_donnerHospital.setRequestFocusEnabled(false);

        cb_bloadgroup.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cb_bloadgroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        cb_bloadgroup.setRequestFocusEnabled(false);

        bt_save.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        bt_save.setText("Save");
        bt_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_save.setFocusable(false);
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(250, 250, 250));
        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel14.setText("Address Street");

        tf_addressNo.setBackground(new java.awt.Color(250, 250, 250));
        tf_addressNo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_addressNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_addressNo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel15.setBackground(new java.awt.Color(250, 250, 250));
        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel15.setText("Address No");

        tf_addressStreet.setBackground(new java.awt.Color(250, 250, 250));
        tf_addressStreet.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_addressStreet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_addressStreet.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel16.setBackground(new java.awt.Color(250, 250, 250));
        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel16.setText("Address Town");

        tf_addressTown.setBackground(new java.awt.Color(250, 250, 250));
        tf_addressTown.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_addressTown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_addressTown.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel17.setBackground(new java.awt.Color(250, 250, 250));
        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel17.setText("Cause Of Death");

        tf_causeOfDeth.setBackground(new java.awt.Color(250, 250, 250));
        tf_causeOfDeth.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_causeOfDeth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_causeOfDeth.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel18.setBackground(new java.awt.Color(250, 250, 250));
        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel18.setText("Brain Death Date");

        tf_brain_deth_date.setBackground(new java.awt.Color(250, 250, 250));
        tf_brain_deth_date.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_brain_deth_date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_brain_deth_date.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel19.setBackground(new java.awt.Color(250, 250, 250));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel19.setText("Past History Of Drug Abuse");

        jLabel20.setBackground(new java.awt.Color(250, 250, 250));
        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel20.setText("Past History Of Malignancies");

        jLabel21.setBackground(new java.awt.Color(250, 250, 250));
        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel21.setText("ICU Days");

        tf_icu.setBackground(new java.awt.Color(250, 250, 250));
        tf_icu.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_icu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_icu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel22.setBackground(new java.awt.Color(250, 250, 250));
        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel22.setText("BMI");

        tf_bmi.setBackground(new java.awt.Color(250, 250, 250));
        tf_bmi.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_bmi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_bmi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel25.setBackground(new java.awt.Color(250, 250, 250));
        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel25.setText("SGOT");

        tf_sgot.setBackground(new java.awt.Color(250, 250, 250));
        tf_sgot.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_sgot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_sgot.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel26.setBackground(new java.awt.Color(250, 250, 250));
        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel26.setText("SGPT");

        tf_sgpt.setBackground(new java.awt.Color(250, 250, 250));
        tf_sgpt.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_sgpt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_sgpt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel27.setBackground(new java.awt.Color(250, 250, 250));
        jLabel27.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel27.setText("Steatotic Liver");

        tf_liver.setBackground(new java.awt.Color(250, 250, 250));
        tf_liver.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_liver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_liver.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel28.setBackground(new java.awt.Color(250, 250, 250));
        jLabel28.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel28.setText("Sodiam");

        tf_sodiam.setBackground(new java.awt.Color(250, 250, 250));
        tf_sodiam.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_sodiam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_sodiam.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel29.setBackground(new java.awt.Color(250, 250, 250));
        jLabel29.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel29.setText("Bilirubin ");

        tf_bilirubin.setBackground(new java.awt.Color(250, 250, 250));
        tf_bilirubin.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_bilirubin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_bilirubin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel30.setBackground(new java.awt.Color(250, 250, 250));
        jLabel30.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel30.setText("Cadaver Type");

        tf_cadaverType.setBackground(new java.awt.Color(250, 250, 250));
        tf_cadaverType.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_cadaverType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_cadaverType.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel32.setBackground(new java.awt.Color(250, 250, 250));
        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel32.setText("White Bload Plates");

        tf_whiteBlodPlates.setBackground(new java.awt.Color(250, 250, 250));
        tf_whiteBlodPlates.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        tf_whiteBlodPlates.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_whiteBlodPlates.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ta_historyOfDrug.setColumns(20);
        ta_historyOfDrug.setRows(5);
        jScrollPane2.setViewportView(ta_historyOfDrug);

        ta_historyOfMalignancies.setColumns(20);
        ta_historyOfMalignancies.setRows(5);
        jScrollPane3.setViewportView(ta_historyOfMalignancies);

        jLabel33.setBackground(new java.awt.Color(250, 250, 250));
        jLabel33.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel33.setText("HIV Status");

        jLabel34.setBackground(new java.awt.Color(250, 250, 250));
        jLabel34.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel34.setText("HBV Status");

        bg_hiv.add(rb_hiv_yes);
        rb_hiv_yes.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        rb_hiv_yes.setText("Yes");
        rb_hiv_yes.setFocusPainted(false);
        rb_hiv_yes.setFocusable(false);
        rb_hiv_yes.setOpaque(false);

        bg_hiv.add(rb_hiv_no);
        rb_hiv_no.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        rb_hiv_no.setSelected(true);
        rb_hiv_no.setText("No");
        rb_hiv_no.setFocusPainted(false);
        rb_hiv_no.setFocusable(false);
        rb_hiv_no.setOpaque(false);

        bg_hbv.add(rb_hbv_yes);
        rb_hbv_yes.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        rb_hbv_yes.setText("Yes");
        rb_hbv_yes.setFocusPainted(false);
        rb_hbv_yes.setFocusable(false);
        rb_hbv_yes.setOpaque(false);

        bg_hbv.add(rb_hbv_no);
        rb_hbv_no.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        rb_hbv_no.setSelected(true);
        rb_hbv_no.setText("No");
        rb_hbv_no.setFocusPainted(false);
        rb_hbv_no.setFocusable(false);
        rb_hbv_no.setOpaque(false);

        jLabel35.setBackground(new java.awt.Color(250, 250, 250));
        jLabel35.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel35.setText("HCV Status");

        bg_hcv.add(rb_hcv_yes);
        rb_hcv_yes.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        rb_hcv_yes.setText("Yes");
        rb_hcv_yes.setFocusPainted(false);
        rb_hcv_yes.setFocusable(false);
        rb_hcv_yes.setOpaque(false);

        bg_hcv.add(rb_hcv_no);
        rb_hcv_no.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        rb_hcv_no.setSelected(true);
        rb_hcv_no.setText("No");
        rb_hcv_no.setFocusPainted(false);
        rb_hcv_no.setFocusable(false);
        rb_hcv_no.setOpaque(false);

        jLabel36.setBackground(new java.awt.Color(250, 250, 250));
        jLabel36.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel36.setText("HLA");

        cb_hla_class_type.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cb_hla_class_type.setRequestFocusEnabled(false);

        cb_hla_class.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cb_hla_class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class 1", "Class 2" }));
        cb_hla_class.setRequestFocusEnabled(false);
        cb_hla_class.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_hla_classPropertyChange(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(250, 250, 250));
        jLabel37.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel37.setText("DSA");

        cb_dsa_class.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cb_dsa_class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class 1", "Class 2" }));
        cb_dsa_class.setRequestFocusEnabled(false);

        jLabel38.setBackground(new java.awt.Color(250, 250, 250));
        jLabel38.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel38.setText("PRA");

        tf_pra.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N

        cb_donnerHospita_province.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cb_donnerHospita_province.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WP", "CP", "NP", "EP", "SP", "NWP", "NCP", "UP", "SBP" }));
        cb_donnerHospita_province.setRequestFocusEnabled(false);
        cb_donnerHospita_province.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_donnerHospita_provincePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_save, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(tf_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(tf_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(tf_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(tf_pno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel7)
                                                            .addComponent(tf_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel15))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel6)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(rb_male)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(rb_female, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jLabel8))
                                                        .addGap(164, 164, 164))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(dc_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel14)
                                                    .addComponent(tf_addressNo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf_addressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_height, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_addressTown, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_whiteBlodPlates)
                                    .addComponent(cb_bloadgroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_sgot)
                                    .addComponent(jScrollPane3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rb_hcv_yes)
                                                .addGap(10, 10, 10)
                                                .addComponent(rb_hcv_no))
                                            .addComponent(jLabel35))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel38)
                                            .addComponent(tf_pra)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel25)
                                            .addComponent(cb_citizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(cb_donnerHospita_province, 0, 1, Short.MAX_VALUE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(8, 8, 8)
                                                .addComponent(cb_donnerHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel36)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29)
                                            .addComponent(cb_hla_class, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cb_hla_class_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel30)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(tf_liver, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_bilirubin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_cadaverType)
                                            .addComponent(jLabel28)
                                            .addComponent(tf_sodiam, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(tf_causeOfDeth, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(tf_brain_deth_date, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel21)
                                                    .addComponent(tf_icu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel22)
                                                    .addComponent(tf_bmi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel26)
                                        .addComponent(tf_sgpt, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(jLabel19)
                                        .addComponent(jScrollPane2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rb_hiv_yes)
                                                .addGap(10, 10, 10)
                                                .addComponent(rb_hiv_no))
                                            .addComponent(jLabel37))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rb_hbv_yes)
                                                .addGap(10, 10, 10)
                                                .addComponent(rb_hbv_no))
                                            .addComponent(jLabel34)))
                                    .addComponent(cb_dsa_class, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(365, 365, 365)))
                        .addGap(43, 43, 43)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cb_citizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf_pno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(tf_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(5, 5, 5)
                                                        .addComponent(tf_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel11))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(tf_addressNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cb_donnerHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cb_donnerHospita_province, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(9, 9, 9)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel12))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(tf_addressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cb_bloadgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel2)
                                                            .addComponent(jLabel5))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(tf_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(dc_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addGap(9, 9, 9)
                                                                .addComponent(tf_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(rb_male, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(rb_female, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel4)
                                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(tf_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(tf_height, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(tf_addressTown, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(7, 7, 7)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel17)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tf_causeOfDeth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel19)
                                                                .addGap(46, 46, 46))))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel20)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_brain_deth_date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_icu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tf_sgot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_bmi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(321, 321, 321)
                                        .addComponent(jScrollPane2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel32))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tf_sgpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_whiteBlodPlates, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_liver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_sodiam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_bilirubin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel33)
                                        .addComponent(jLabel30))
                                    .addComponent(jLabel34)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel35)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb_hcv_yes)
                                    .addComponent(rb_hcv_no)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_hiv_yes)
                            .addComponent(rb_hiv_no)
                            .addComponent(rb_hbv_yes)
                            .addComponent(rb_hbv_no))
                        .addComponent(tf_cadaverType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_pra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_hla_class, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_hla_class_type, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_dsa_class, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_donnerHospita_provincePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_donnerHospita_provincePropertyChange

        System.out.println("Province Code - " + cb_donnerHospita_province.getSelectedItem().toString());
        loadHospitals(cb_donnerHospita_province.getSelectedItem().toString());

    }//GEN-LAST:event_cb_donnerHospita_provincePropertyChange

    private void cb_hla_classPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_hla_classPropertyChange

        System.out.println("HLA Class - " + cb_hla_class.getSelectedItem().toString());
        loadHLA(cb_hla_class.getSelectedItem().toString());

    }//GEN-LAST:event_cb_hla_classPropertyChange

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed

        try {

            Session s = HibernateUtil.getSessionFactory().openSession();

            Doner doner = new Doner();
            doner.setDonerFname(tf_fname.getText());
            doner.setDonerMname(tf_mname.getText());
            doner.setDonerLname(tf_lname.getText());
            doner.setDonerNic(tf_nic.getText());
            doner.setDonerCauseOfDeath(tf_causeOfDeth.getText());
            doner.setDonerIcuDays(tf_icu.getText());
            doner.setDonerSteatoticLiver(Integer.parseInt(tf_liver.getText()));
            doner.setDonerBilirubin(Integer.parseInt(tf_bilirubin.getText()));
            doner.setDonerHla(cb_hla_class.getSelectedItem().toString() + "," + cb_hla_class_type.getSelectedItem().toString());
            doner.setDonerPhone(tf_pno.getText());
            doner.setDonerDob(new SimpleDateFormat("dd-mm-yyyy").format(dc_dob.getDate()));
            if (rb_male.isSelected()) {
                doner.setDonerGen("Male");
            } else {
                doner.setDonerGen("Female");
            }
            doner.setDonerHeight(tf_height.getText());
            doner.setDonerBrainDeathDate(tf_brain_deth_date.getText());
            doner.setDonerBmi(tf_bmi.getText());
            doner.setDonerSodiam(tf_sodiam.getText());
            doner.setDonerCadaverType(tf_cadaverType.getText());
            doner.setDonerWeight(tf_weight.getText());

            AddressDoner addressDoner = new AddressDoner();
            addressDoner.setAddressDonerNo(tf_addressNo.getText());
            addressDoner.setAddressDonerStreet(tf_addressStreet.getText());
            addressDoner.setAddressDonerTown(tf_addressTown.getText());
            
            doner.setAddressDoner(addressDoner);
            
            doner.setDonerPastHistoryDrug(ta_historyOfDrug.getText());
            doner.setDonerSgpt(tf_sgpt.getText());
            if (rb_hiv_yes.isSelected()) {
                doner.setDonerHivStatus("Yes");
            } else {
                doner.setDonerHivStatus("No");
            }

            if (rb_hbv_yes.isSelected()) {
                doner.setDonerHbvStatus("Yes");
            } else {
                doner.setDonerHbvStatus("No");
            }

            doner.setDonerDsa(cb_dsa_class.getSelectedItem().toString());

            doner.setDonerCuntry(cb_citizenship.getSelectedItem().toString());

            Criteria c = s.createCriteria(DonerHostpital.class);
            c.add(Restrictions.eq("donerHostpitalName", cb_donnerHospital.getSelectedItem().toString()));
            c.add(Restrictions.eq("donerHostpitalProvince", cb_donnerHospita_province.getSelectedItem().toString()));

            DonerHostpital donerHostpital = (DonerHostpital) c.uniqueResult();
            doner.setDonerHostpital(donerHostpital);

            doner.setDonerBlodGroup(cb_bloadgroup.getSelectedItem().toString());
            doner.setDonerPastHistoryMalignancies(ta_historyOfMalignancies.getText());
            doner.setDonerSgot(tf_sgot.getText());
            doner.setDonerWhiteBloadPlates(tf_whiteBlodPlates.getText());

            if (rb_hcv_yes.isSelected()) {
                doner.setDonerHcvStatus("Yes");
            } else {
                doner.setDonerHcvStatus("No");
            }

            doner.setDonerPra(tf_pra.getText());
            
            doner.setDonerRegdate(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
            doner.setDonerStatus("Active");
            doner.setDonerAvailable("1");
            
            int doner_birth_year=Integer.parseInt(new SimpleDateFormat("YYYY").format(dc_dob.getDate()));
            int thisYear=Integer.parseInt(new SimpleDateFormat("yyyy").format(new Date()));
            
            int age=thisYear-doner_birth_year;
            
            doner.setDonerAge(age+"");
           
            s.save(addressDoner);
             s.save(doner);

            s.beginTransaction().commit();

        } catch (Exception e) {

            e.printStackTrace();

        }

    }//GEN-LAST:event_bt_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_hbv;
    private javax.swing.ButtonGroup bg_hcv;
    private javax.swing.ButtonGroup bg_hiv;
    private javax.swing.JButton bt_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_bloadgroup;
    private javax.swing.JComboBox<String> cb_citizenship;
    private javax.swing.JComboBox<String> cb_donnerHospita_province;
    private javax.swing.JComboBox<String> cb_donnerHospital;
    private javax.swing.JComboBox<String> cb_dsa_class;
    private javax.swing.JComboBox<String> cb_hla_class;
    private javax.swing.JComboBox<String> cb_hla_class_type;
    private com.toedter.calendar.JDateChooser dc_dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_hbv_no;
    private javax.swing.JRadioButton rb_hbv_yes;
    private javax.swing.JRadioButton rb_hcv_no;
    private javax.swing.JRadioButton rb_hcv_yes;
    private javax.swing.JRadioButton rb_hiv_no;
    private javax.swing.JRadioButton rb_hiv_yes;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JTextArea ta_historyOfDrug;
    private javax.swing.JTextArea ta_historyOfMalignancies;
    private javax.swing.JTextField tf_addressNo;
    private javax.swing.JTextField tf_addressStreet;
    private javax.swing.JTextField tf_addressTown;
    private javax.swing.JTextField tf_bilirubin;
    private javax.swing.JTextField tf_bmi;
    private javax.swing.JTextField tf_brain_deth_date;
    private javax.swing.JTextField tf_cadaverType;
    private javax.swing.JTextField tf_causeOfDeth;
    private javax.swing.JTextField tf_fname;
    private javax.swing.JTextField tf_height;
    private javax.swing.JTextField tf_icu;
    private javax.swing.JTextField tf_liver;
    private javax.swing.JTextField tf_lname;
    private javax.swing.JTextField tf_mname;
    private javax.swing.JTextField tf_nic;
    private javax.swing.JTextField tf_pno;
    private javax.swing.JTextField tf_pra;
    private javax.swing.JTextField tf_sgot;
    private javax.swing.JTextField tf_sgpt;
    private javax.swing.JTextField tf_sodiam;
    private javax.swing.JTextField tf_weight;
    private javax.swing.JTextField tf_whiteBlodPlates;
    // End of variables declaration//GEN-END:variables

    private void loadCuntrys() {

        try {

            String[] locales = Locale.getISOCountries();
            Vector v = new Vector();
            v.add("Sri Lankan");
            for (String countryCode : locales) {

                Locale obj = new Locale("", countryCode);
                v.add(obj.getDisplayCountry());
                System.out.println("Country Code = " + obj.getCountry()
                        + ", Country Name = " + obj.getDisplayCountry());

            }
            DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(v);
            cb_citizenship.setModel(defaultComboBoxModel);

        } catch (Exception e) {

            e.printStackTrace();

        }

    }

    private void loadHospitals(String code) {

        try {
            Session s = HibernateUtil.getSessionFactory().openSession();
            Criteria cForLoadHospitals = s.createCriteria(DonerHostpital.class);
            cForLoadHospitals.add(Restrictions.eq("donerHostpitalProvince", code));
            cForLoadHospitals.add(Restrictions.eq("donerHostpitalStatus", "Active"));
            List<DonerHostpital> li = cForLoadHospitals.list();
            Vector v = new Vector();
            for (DonerHostpital donerHostpital : li) {
                v.add(donerHostpital.getDonerHostpitalName().toString());
            }
            DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(v);
            cb_donnerHospital.setModel(defaultComboBoxModel);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void loadHLA(String Hlaclass) {

        Vector v = new Vector();

        if (Hlaclass.equals("Class 1")) {

            v.add("A");
            v.add("B");
            v.add("C");

        } else {

            v.add("DR");
            v.add("DQ");
            v.add("DP");

        }
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(v);
        cb_hla_class_type.setModel(defaultComboBoxModel);

    }
}
